name: single_district
channels:
  - bioconda
  - gurobi
  - conda-forge
  - https://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - atlite
  - memory_profiler
  - netcdf4
  - rasterio!=1.2.10
  - descartes
  - country_converter
  - scipy
  - geopandas[version='>=0.11.0']
  - fiona[version='<=1.18.20']
  - python[version='==3.10']
  - yaml
  - networkx
  - powerplantmatching[version='>=0.5.4']
  - progressbar2
  - xlrd
  - numpy[version='<=1.23.5']
  - pycountry
  - matplotlib
  - pyomo
  - dask
  - pytz
  - pyxlsb
  - proj
  - openpyxl
  - pypsa[version='==0.25.0']
  - pip
  - cartopy
  - pandas
  - geopy
  - shapely[version='<2.0']
  - tabula-py
  - tqdm
  - snakemake-minimal
  - ipython
  - pytables
  - lxml
  - seaborn
  - xarray
  - glpk
  - gurobi[version='==10.0.0']
  - ipopt
  - jupyter
  - xlsxwriter
  - jupyterlab
  - squarify
  - plotly
